const MESSAGES = {
  COMMANDS: {
    BOT: {
      BOTINFO: {
        name: 'botinfo',
        aliases: ['bot', 'info'],
        description: `Affiche les informations sur le bot`,
        category: 'bot',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      EVAL: {
        name: 'eval',
        aliases: [],
        description: `Permet d'évaluer le code`,
        category: 'bot',
        permissions: true,
        permissionFlag: 'ADMINISTRATOR',
        isUserAdmin: false,
        usage: '[code]',
        args: false,
      },
      HELP: {
        name: 'help',
        aliases: ['commands', 'list'],
        description: `Affiche la liste des commandes et de leurs informations une par une`,
        category: 'bot',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '[commande]',
        args: false,
      },
      PING: {
        name: 'ping',
        aliases: ['latence', 'pong'],
        description: `Affiche la latence du bot`,
        category: 'bot',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      }
    },
    FUN: {
      DICE: {
        name: 'dice',
        aliases: ['dé'],
        description : `Lance un dé à 6 faces`,
        category: 'fun',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      JOKE: {
        name: 'joke',
        aliases: ['blague'],
        description : `Affiche une blague choisie au hasard`,
        category: 'fun',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      LOVE: {
        name: 'love',
        aliases: ['affinity', 'amour', 'calclove'],
        description : `Affiche le poucentage d'amour entre deux utilisateur`,
        category: 'fun',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<@mention>',
        args: true,
      },
      QUESTION: {
        name: 'question',
        aliases: ['8ball', 'ask'],
        description : `Répond à une question posée`,
        category: 'fun',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<question>',
        args: true,
      },
      RPS: {
        name: 'rps',
        aliases: ['pfc', 'rock'],
        description : `Joue à Pierre, papier, ciseaux`,
        category: 'fun',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<pierre/papier/ciseaux>',
        args: true,
      },
      SHOOT: {
        name: 'shoot',
        aliases: ['kill', 'tuer'],
        description : `Tue l'utilisateur mentionné`,
        category: 'fun',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<@mention>',
        args: true,
      },
    },
    MISC: {
      AVATAR: {
        name: 'avatar',
        aliases: ['logo', 'picture'],
        description: `Affiche l'avatar d'une personne`,
        category: 'misc',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '[@mention]',
        args: false,
      },
      CALC: {
        name: 'calc',
        aliases: [],
        description: `Calcule une expression`,
        category: 'misc',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<calcul>',
        args: true,
      },
      FANCYTEXT: {
        name: 'fancytext',
        aliases: ['emojitext', 'fancy'],
        description: `Utilise les emojis pour écrire un texte`,
        category: 'misc',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<message>',
        args: true,
      },
      FLIPTEXT: {
        name: 'fliptext',
        aliases: ['flip'],
        description: `Renverse un texte`,
        category: 'misc',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<message>',
        args: true,
      },
      INFOEMOJI: {
        name: 'infoemoji',
        aliases: ['emoji', 'emote', 'infoemote'],
        description: `Affiche les informations sur l'emoji`,
        category: 'misc',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<:emoji:>',
        args: true,
      },
      INSTAGRAM: {
        name: 'instagram',
        aliases: ['insta'],
        description : `Affiche un profil Instagram`,
        category: 'misc',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<compte>',
        args: true,
      },
      POLL: {
        name: 'poll',
        aliases: ['quickpoll', 'sondage'],
        description: `Lance un sondage`,
        category: 'misc',
        permissions: true,
        permissionFlag: 'SEND_TTS_MESSAGES',
        isUserAdmin: false,
        usage: '<message>',
        args: true,
      },
      SAY: {
        name: 'say',
        aliases: ['repeat'],
        description: `Fait parler le bot`,
        category: 'misc',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<message>',
        args: true,
      },
      SERVERINFO: {
        name: 'serverinfo',
        aliases: ['guild', 'server', 'serverstats', 'si'],
        description: `Affiche les informations du serveur`,
        category: 'misc',
        permissions: false,
        permissionFlag: "",
        isUserAdmin: false,
        usage: "",
        args: false,
      },
      USERINFO: {
        name: 'userinfo',
        aliases: ['ui', 'user', 'userstats'],
        description: `Affiche les informations d'un utilisateur`,
        category: 'misc',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
    },
    MOD: {
      BAN: {
        name: 'ban',
        aliases: [],
        description: `Ban un utilisateur`,
        category: 'mod',
        permissions: true,
        permissionFlag: 'BAN_MEMBERS',
        isUserAdmin: true,
        usage: '<@mention> [raison]',
        args: true,
      },
      KICK: {
        name: 'kick',
        aliases: [],
        description: `Exclure un utilisateur`,
        category: 'mod',
        permissions: true,
        permissionFlag: 'KICK_MEMBERS',
        isUserAdmin: true,
        usage: '<@mention> [raison]',
        args: true,
      },
      MUTE: {
        name: 'mute',
        aliases: ['chut', 'muet'],
        description: `Rend muet un utilisateur`,
        category: 'mod',
        permissions: true,
        permissionFlag: 'MUTE_MEMBERS',
        isUserAdmin: true,
        usage: '<@mention> [temps] [raison]',
        args: true,
      },
      PRUNE: {
        name: "prune",
        aliases: [],
        description: `Supprime les messages d'un utilisateur`,
        category: 'mod',
        permissions: true,
        permissionFlag: 'MANAGE_MESSAGES',
        isUserAdmin: true,
        usage: '<@mention> <nombre>',
        args: true,
      },
      PURGE: {
        name: "purge",
        aliases: ['clear', 'suppr'],
        description: `Supprime les messages dans un salon donné`,
        category: 'mod',
        permissions: true,
        permissionFlag: 'MANAGE_MESSAGES',
        isUserAdmin: false,
        usage: '<nombre>',
        args: true,
      },
      UNBAN: {
        name: "unban",
        aliases: ['deban'],
        description: `Supprime le bannissement d'un utilisateur`,
        category: 'mod',
        permissions: true,
        permissionFlag: 'BAN_MEMBERS',
        isUserAdmin: false,
        usage: '<identifiant>',
        args: true,
      },
      UNMUTE: {
        name: "unmute",
        aliases: ['demute'],
        description: `Rend la parole à une personne muette`,
        category: 'mod',
        permissions: true,
        permissionFlag: 'MUTE_MEMBERS',
        isUserAdmin: true,
        usage: '<@mention>',
        args: true,
      },
    },
    MONEY: {
      COINFLIP: {
        name: 'coinflip',
        aliases: ['coin', 'flip'],
        description: `Fait un pari sur un lancé une pièce`,
        category: 'money',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<argent> <pile/face>',
        args: true,
      },
      DAILY: {
        name: 'daily',
        aliases: [],
        description: `Donne de l'argent quotidiennement`,
        category: 'money',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      GIVE: {
        name: 'give',
        aliases: [],
        description: `Donne de l'argent à l'utilisateur mentionné`,
        category: 'money',
        permissions: true,
        permissionFlag: 'ADMINISTRATOR',
        isUserAdmin: false,
        usage: '<@mention> <montant>',
        args: true,
      },
      LEADERBOARD: {
        name: 'leaderboard',
        aliases: ['lb', 'leader'],
        description: `Affiche le classement Money ou Réputation`,
        category: 'money',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '[rep]',
        args: false,
      },
      PROFIL: {
        name: 'profil',
        aliases: ['me', 'money'],
        description: `Affiche le profil de l'utilisateur`,
        category: 'money',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '[@mention]',
        args: false,
      },
      REPUTATION: {
        name: 'reputation',
        aliases: ['point', 'rep'],
        description: `Donne un point de réputation à l'utilisateur`,
        category: 'money',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<@mention>',
        args: true,
      },
      SEND: {
        name: 'send',
        aliases: [],
        description: `Envoie de l'argent à l'utilisateur`,
        category: 'money',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<@mention> <montant>',
        args: false,
      },
      WORK: {
        name: 'work',
        aliases: [],
        description: `Travaille pour gagner de l'argent`,
        category: 'money',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      WORKS: {
        name: 'works',
        aliases: [],
        description: `Affiche la liste des métiers et permet d'être recruté dans l'un d'eux`,
        category: 'money',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '[nombre]',
        args: false,
      },
    },
    MUSIC: {
      CLEARQUEUE: {
        name: 'clearqueue',
        aliases: ['cq', 'qc', 'queueclear'],
        description: `Supprime les musiques de la queue`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      FILTER: {
        name: "filter",
        aliases: ['effect', 'filtre'],
        description: `Ajoute un filtre à la queue en cours`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<filtre>',
        args: true,
      },
      FILTERS: {
        name: 'filters',
        aliases: ['effectlist', 'filterslist'],
        description: `Affiche la liste des filtres`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      LOOP: {
        name: 'loop',
        aliases: ['boucle', 'replay'],
        description: `Met en boucle une musique`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      LYRICS: {
        name: 'lyrics',
        aliases: ['l', 'paroles'],
        description: `Affiche les paroles de la musique en cours ou d'une recherchée`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '[musique]',
        args: false,
      },
      NOWPLAYING: {
        name: 'nowplaying',
        aliases: ['np', 'time', 'timeleft', 'tl'],
        description: `Affiche les informations sur la musique en cours`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      PAUSE: {
        name: 'pause',
        aliases: [],
        description: `Met en pause la musique en cours`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      PLAY: {
        name: 'play',
        aliases: ['joue', 'p', 'song'],
        description: `Joue la musique sélectionnée`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<musique>',
        args: true,
      },
      QUEUE: {
        name: 'queue',
        aliases: ['list', 'q'],
        description: `Affiche la queue en cours`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      RESUME: {
        name: 'resume',
        aliases: [],
        description: "Relance la queue en cours",
        category: 'music',
        permissions: false,
        permissionFlag: "",
        isUserAdmin: false,
        usage: "",
        args: false,
      },
      SHUFFLE: {
        name: 'shuffle',
        aliases: ['aléatoire', 'mélange', 'random'],
        description: `Tri de façon aléatoire la queue`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      SKIP: {
        name: 'skip',
        aliases: ['s', 'sauter'],
        description: `Saute une musique`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      STOP: {
        name: 'stop',
        aliases: [],
        description: `Arrête la lecture`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '',
        args: false,
      },
      VOLUME: {
        name: 'volume',
        aliases: [],
        description: `Modifie le volume de la queue`,
        category: 'music',
        permissions: false,
        permissionFlag: '',
        isUserAdmin: false,
        usage: '<nombre>',
        args: true,
      },
    },
  }
};

exports.MESSAGES = MESSAGES;